# all from https://github.com/rwinlib

name: bundle binaries

on:
  workflow_dispatch:
    inputs:
      kiwiVersion:
        description: 'Target Version of kiwi'
        required: false
        default: 'v0.13.1'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'mrchypark@gmail.com'
          git config --global user.name  'Chanyub Park (via CI)'
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git
          update: true

      - name: Switch to Rtools
        run: |
          msys2 -c 'cp -f pacman.conf /etc/pacman.conf'
          msys2 -c 'pacman --noconfirm -Syyuu'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: install cmake
        run: pacman -Syu --noconfirm make cmake
        env:
          PACMAN_REPOSITORY: rtools
        shell: msys2 {0}

      - name: kiwi
        run: |
          cd D:\\a\\rwinlib-elbird
          git clone -b ${{ github.event.inputs.kiwiVersion }} --depth 1 https://github.com/bab2min/Kiwi
          cd Kiwi
          git rm third_party/mimalloc
          git rm third_party/googletest
          git rm third_party/cpuinfo
          git submodule update --init --recursive
          mkdir b64
          mkdir b32
          mkdir ucrt
          cd b64
          MINGW_ARCH=mingw64 cmake -DCMAKE_BUILD_TYPE=Release -DKIWI_BUILD_TEST=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
          MINGW_ARCH=mingw64 make kiwi_static
        shell: msys2 {0}
