# all from https://github.com/rwinlib

name: bundle binaries

on:
  workflow_dispatch:
    inputs:
      kiwiVersion:
        description: 'Target Version of kiwi'
        required: false
        default: 'v0.13.0'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  }

    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'mrchypark@gmail.com'
          git config --global user.name  'Chanyub Park (via CI)'
      
      - uses: actions/checkout@v2

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2  
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p

      - name: Switch to Rtools
        run: |
          msys2 -c 'cp -f pacman.conf /etc/pacman.conf'
          msys2 -c 'pacman --noconfirm -Syyuu'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: install cmake
        run: pacman -Syu --noconfirm gcc make cmake
        env:
          PACMAN_REPOSITORY: rtools
        shell: msys2 {0}

      - name: kiwi
        run: |
          version=${{ github.event.inputs.kiwiVersion }}
          cd D:\\a\\rwinlib-elbird
          git clone -b $version --depth 1 https://github.com/bab2min/Kiwi
          cd Kiwi
          git rm third_party/mimalloc
          git rm third_party/googletest
          git rm third_party/cpuinfo
          git submodule update --init --recursive
          mkdir b64
          mkdir b32
          mkdir ucrt
          cd b64
          cmake -DCMAKE_BUILD_TYPE=Release -DKIWI_BUILD_TEST=OFF -DKIWI_USE_CPUINFO=OFF -DKIWI_USE_MIMALLOC=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
          make kiwi_static
          cp libkiwi_static.a ../../rwinlib-elbird/lib/x64/libkiwi.a
          cd ../b32
          MINGW_ARCH=MINGW32 cmake -DCMAKE_BUILD_TYPE=Release -DKIWI_BUILD_TEST=OFF -DKIWI_USE_CPUINFO=OFF -DKIWI_USE_MIMALLOC=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
          MINGW_ARCH=MINGW32 make kiwi_static
          cp libkiwi_static.a ../../rwinlib-elbird/lib/i386/libkiwi.a
          cd ../ucrt
          MINGW_ARCH=UCRT64 cmake -DCMAKE_BUILD_TYPE=Release -DKIWI_BUILD_TEST=OFF -DKIWI_USE_CPUINFO=OFF -DKIWI_USE_MIMALLOC=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
          MINGW_ARCH=UCRT64 make kiwi_static    
          cp libkiwi_static.a ../../rwinlib-elbird/lib/x64-ucrt/libkiwi.a
          cd ../
          cp -r include ../include
          
        shell: msys2 {0}

      - name: Push binaries
        run: |
          version=${{ github.event.inputs.kiwiVersion }}
          git add include lib*
          git commit -m "Bundle $version ($(date +%F))" || exit 0
          git tag $version
          git push origin main $version
        shell: bash