# all from https://github.com/rwinlib

name: bundle binaries

on:
  workflow_dispatch:
    inputs:
      kiwiVersion:
        description: 'Target Version of kiwi'
        required: false
        default: 'v0.13.1'


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'mrchypark@gmail.com'
          git config --global user.name  'Chanyub Park (via CI)'
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          rtools-version: 40
          update-rtools: true
      - name: install cmake on x64
        run: |
          pacman -Sy mingw-w64-x86_64-cmake
        shell: C:\rtools40\mingw64\bin\bash.exe --login {0}
      - name: install cmake on x32
        run: |
          pacman -Sy mingw-w32-i686-cmake
        shell: C:\rtools40\mingw32\bin\bash.exe --login {0}
      - name: install cmake on ucrt
        run: |
          pacman -Sy mingw-w64-x86_64-cmake
        shell: C:\rtools40\ucrt64\bin\bash.exe --login {0}
      - name: Push binaries
        run: |
          version=${{ steps.download.outputs.VERSION }}
          git add README.md include share lib*
          git commit -m "Bundle $version ($(date +%F))" || exit 0
          git tag $version
          git push origin master $version
        shell: bash