# all from https://github.com/rwinlib

name: bundle binaries

on:
  workflow_dispatch:
    inputs:
      kiwiVersion:
        description: 'Target Version of kiwi'
        required: false
        default: 'v0.13.1'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'mrchypark@gmail.com'
          git config --global user.name  'Chanyub Park (via CI)'
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          rtools-version: 40
          update-rtools: true
      - name: install cmake
        run: |
          pacman -Syu --noconfirm mingw-w64-x86_64-cmake mingw-w64-i686-cmake mingw-w64-ucrt-x86_64-cmake
        shell: c:\rtools40\usr\bin\bash.exe --login {0}

      - name: cmake test
        run: |
          cmake
        shell: c:\rtools40\mingw64.exe

      - name: kiwi
        run: |
          cd D:\\a\\rwinlib-elbird
          git clone -b ${{ github.event.inputs.kiwiVersion }} --depth 1 https://github.com/bab2min/Kiwi
          cd Kiwi
          git rm third_party/mimalloc
          git rm third_party/googletest
          git rm third_party/cpuinfo
          git submodule update --init --recursive
          mkdir b64
          mkdir b32
          mkdir ucrt
          cd b64
          MINGW_ARCH=mingw64 cmake -DCMAKE_BUILD_TYPE=Release -DKIWI_BUILD_TEST=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
          MINGW_ARCH=mingw64 make kiwi_static
          
        shell: c:\rtools40\usr\bin\bash.exe --login {0}
